import { getBaseUrl } from "../../config";
import { generateRandomString } from "./utils";

const baseUrl = getBaseUrl();

export default {
    loginUrl: `${baseUrl}/auth/login`,
    homeUrl: `${baseUrl}/cms/solar/portfolio/home`,
};

export const unitVariables = {
    Placeholder: "Input Unit Name",
    CreateSuccess: "Unit Added Successfully!!",
    Select: "Control+A",
    Delete: "Backspace",
    Alert: "Please Input Unit Name!",
    UpdateSuccess: "Unit Updated Successfully!!",
    DeleteSuccess: "Unit Deleted Successfully!!"
};

export const jobTagVariables = {
    Placeholder: "Job Tag Name",
    CreateSuccess: "Job tag Added successfully!!",
    Select: "Control+A",
    Delete: "Backspace",
    Alert: "Please input Job Tag Name!",
    DeleteSuccess: "Job Tag Removed successfully!!"
};

export const wmsVariables = {
    wmsHeaderText: "POA",
    wmsHeaderText01:"GHI",
    wmsheaderText02:"Module Temp",
    wmsheaderText03:"Ambient Temp",
    wmsExportButton:"Export csv",
    wmsParameterheader:"Median WMS",
    wmsTableHeader:"Parameters",
    wmsTableHeader01:"Unit",
    wmsTableHeader02:"Median",
    wmsIs2Text:"Date & Time",
    wmsIs2TextUnit:"POA (W/m²)",
    wmsIs2TextUnit01:"GHI (W/m²)",
    wmsIs2TextUnit02:"Module temperature (°C)",
    wmsIs2TextUnit03:"Module temperature 2 (°C)",
    wmsIs2Textunit04:"Ambient Temperature (°C)",
    wmsIs2TextUnit05:"Battery voltage (V)",
    wmsIs2TextUnit06:"Humidity (%)",
    wmsIs2TextUnit07:"Inst Rain (mm)",
    wmsIs2TextUnit08:"Total Rain (mm)",
    wmsIs2TextUnit09:"GHI_DW (W/m²)",
    wmsIs2TextUnit10:"POA_DW (W/m²)",
    wmsIs2TextUnit11:"Wind speed (m/s)",
    wmsIs2TextUnit12:"Wind Direction (°)",
    wmsIs2TextUnit13:"BAR_PRES (Kpa)",
    wmsIs2TextUnit14:"Cloud cover (Okta)",
    wmsIs2TextUnit15:"Diffuse (W/m²)",
    wmsIs2TextUnit16:"Direct (W/m²)",
    wmsIs2TextUnit17:"GLOBAL (W/m²)",
    wmsIs2TextUnit18:"ALBEDO_GHI (%)",
    wmsIs2TextUnit19:"ALBEDO_POA (%)",
    wmsIs2TextUnit20:"Total ghi (kW/m²)",
    wmsIs2TextUnit21:"Total poa (kW/m²)",
    wmsIs2TextUnit22:"Total ghi DW (kW/m²)",
    wmsIs2TextUnit23:"Total poa DW (kW/m²)",
    deviceName:"IS2 WMS",
    deviceName01:"IS6 WMS",
    deviceName02:"IS9 WMS",
    deviceName03:"IS15 WMS",
    deviceName04:"IS19 WMS",
    plantName:"ES Sun Power 20MW",
}

export const inverterKpiVariables ={
    Placeholder: "Start date",
    Placeholder01: "End date",
    KeyboardButton: "Enter",
    Text:"Inverter Monitor",
    disableButton: "Median",
    enableButton: "Max",
    disableButton01: "Inverter",
    enableButton01: "Module",
    trackerOption: "Tracker",
    nonTrackerOption: "Non Tracker",
    text01: "Inverter KPI\'s",
    text02: "Inverter Availability(%)",
    text03: "Avg Inv Yield (MWh/MWp)",
    text04: "Total Inv Generation (kWh)",
    text05: "Avg Inv PR (%)",
    text06: "Efficiency (%)",
    text07: "Total Downtime (minutes)",
    Inverters: [
        'IS30 Inverter 1', 'IS30 Inverter 2', 'IS30 Inverter 3', 'IS30 Inverter 4', 'IS2 Inverter 1', 'IS2 Inverter 2', 'IS2 Inverter 3', 'IS2 Inverter 4', 'IS3 Inverter 1',
        'IS3 Inverter 2','IS3 Inverter 3','IS3 Inverter 4', 'IS4 Inverter 3','IS3 Inverter 4','IS4 Inverter 1','IS4 Inverter 2','IS4 Inverter 3','IS4 Inverter 4','IS5 Inverter 1',
        'IS5 Inverter 2','IS5 Inverter 3','IS5 Inverter 4','IS6 Inverter 1','IS6 Inverter 2','IS6 Inverter 3','IS6 Inverter 4','IS7 Inverter 1','IS7 Inverter 2','IS7 Inverter 3',
        'IS7 Inverter 4','IS8 Inverter 1','IS8 Inverter 2','IS8 Inverter 3','IS8 Inverter 4','IS9 Inverter 1','IS9 Inverter 2','IS9 Inverter 3','IS9 Inverter 4','IS10 Inverter 1',
        'IS10 Inverter 2','IS10 Inverter 3','IS10 Inverter 4','IS11 Inverter 1','IS11 Inverter 2','IS11 Inverter 3','IS11 Inverter 4','IS12 Inverter 1','IS12 Inverter 2','IS12 Inverter 3',
        'IS12 Inverter 4','IS13 Inverter 1','IS13 Inverter 2','IS13 Inverter 3','IS13 Inverter 4','IS14 Inverter 1','IS14 Inverter 2','IS14 Inverter 3',
        'IS14 Inverter 4','IS15 Inverter 1','IS15 Inverter 2','IS15 Inverter 3','IS15 Inverter 4','IS16 Inverter 1','IS16 Inverter 2','IS16 Inverter 3','IS16 Inverter 4'
      ],
    appMenuButton: "Export csv",
    dropDownOption: "PR",
    dropDownOption01: "Yield"

}

export const igbtVariables ={
    pageHeaderText:"Heatmap / Igbt",
    headerText:"Active Power[MW]",
    headerText01:"Daily Production",
    headerText02:"Peak Power",
    headerText03:"KPI",
    headerText04:"PR",
    headerText05:"PA",
    headerText06:"CUFAC",
    headerText07:"Total GHI",
    headerText08:"Total POA",
    headerText09:"WMS",
    headerText10:"Module Temp",
    headerText11:"Ambient Temp",
    headerText12:"Relative Humidity",
    headerText13:"Wind Speed",
    plantnames:[
        'ES Sun Power 20MW',
        'ES Energy Power 10MW',
        'ES Solar Power 10MW',
        'Dres Energy Pvt Ltd. 07MW',
        'Dres Energy Pvt Ltd. 08MW',
        'Prakreetee Solar Energy Godawari Private Limited',
      ],
      placeHolder:"Temp Deviation",
      inputValue:"0",
      setButton:"SET",
      dropDown:"Inverter",
      dropDown01:"Inverter Unit",
      deviceName:"IS30",
      deviceName01:"IS2",
      deviceName02:"IS6",
      deviceName03:"IS7",
      deviceName04:"IS5",
      deviceName05:"IS8",
}


export const storeVariables = {
    NamePlaceholder: "Input Store Name",
    CodePlaceholder: "Input Store Code",
    StorekeeperPlaceholder: "Select Storekeeper",
    PlantdropdownSelector: "#screencontainer > div > app-store-create > div > div > nz-card > div.ant-card-body > div:nth-child(2) > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
    StorekeeperdropdownSelector: "#screencontainer > div > app-store-create > div > div > nz-card > div.ant-card-body > div:nth-child(2) > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
    StreetOnePlaceholder: "Input Street1",
    StreetTwoPlaceholder: "Input Street2",
    CityPlaceholder: "Input City",
    CountryPlaceholder: "Input Country",
    StatePlaceholder: "Input State",
    PincodePlaceholder: "Input Pincode",
    RegionPlaceholder: "Input Region",
    LatitudePlaceholder: "Input Latitude",
    LongitudePlaceholder: "Input Longitude",
    GoogleMapLinkPlaceholder: "Input Google Map Link",
    SubmitbuttonSelector: "#screencontainer > div > app-store-create > div > div > nz-card > div.ant-card-body > div.steps-action.ng-star-inserted > nz-space > div:nth-child(2) > button > span",
    CreateSuccessSelector: "#cdk-overlay-34 > nz-notification-container > div.ant-notification.ant-notification-topRight > nz-notification > div > div > div > div",
    CreateSuccess: "Store Created Successfully!!",
    Enter: "Enter",
    Select: "Control+A",
    Delete: "Backspace",
    NameAlert: "Please Input Store Name!",
    CodeAlert: "Please Input Store Code",
    CodeSizeAlert: "Enter a code of only 8 letters",
    PlantAlert: "Please Select Plant!",
    StorekeeperAlert: "Please Select Storekeeper!",
    StreetOneAlert: "Please Input Street1!",
    StreetTwoAlert: "Please Input Street2!",
    CityAlert: "Please Input City!",
    CountryAlert: "Please Input Country!",
    StateAlert: "Please Input State!",
    PincodeAlert: "Please Input Pincode!",
    RegionAlert: "Please Input Region!",
    LatitudeAlert: "Please Input Latitude!",
    LongitudeAlert: "Please Input Longitude!",
    GoogleMapLinkAlert: "Please Input Google Map Link!",
    UpdateSuccess: "Store Updated Successfully!!",
    NameExistValidation: "Store name already exist",
    DeleteSuccess: "Store Deleted Successfully!!",
    operation: {
        create: "Add",
        submit: "Submit"
    }
};

export const vendor_Type_Variables = {
    operation: {
        create: "Add",
        save: "Save",
        Cancel: "Cancel"
    },
    NamePlaceholder: "Input Vendor Type Name",
    CodePrefixPlaceholder: "Input Vendor Code Prefix",
    FormDropdownLocator: '.ant-select[formcontrolname="formid"][nzplaceholder="Select Form"]',
    CreateSuccess: "Vendor Type Created Successfully!!",
    UpdateSuccess: "Vendor Type Updated Successfully!!",
    Enter: "Enter",
    Select: "Control+A",
    Delete: "Backspace",
    NameAlert: "Please Input Vendor Type Name!",
    CodePrefixSizeAlert: "Only Alphabets And Numbers Can Contain Spaces ,- And Underscore",
    CodePrefixAlert: "Please Input Vendor Code Prefix!",
    FormAlert: "Please Select Form!",
    FormCancelSelector: "#screencontainer > div > app-create-vendor-type > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-dirty.ng-touched > div > div:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    FormEditCancelSelector: 'span[nztype="close-circle"]',
    NameExistAlert: "vendortype name - ",
    NameExistalert: " already exist",
    CodePrefixExistAlert: "vendorcode prefix - ",
    CodePrefixExistalert: " already exist",
    randomCodePrefix: generateRandomString(5),

};

export const part_Type_Variables = {
    operation: {
        create: "Add",
        save: "Save",
        Cancel: "Cancel"
    },
    NamePlaceholder: "Input Part Type Name",
    CodePrefixPlaceholder: "Input Stock Code Prefix",
    randomCodePrefix: generateRandomString(5),
    FormDropdownLocator: '.ant-select[formcontrolname="formid"][nzplaceholder="Select Form"]',
    UnitDropdownLocator: '.ant-select[formcontrolname="unit"][nzplaceholder="Select Unit"]',
    LowerQuantityThresholdPlaceholder: "Input Lower Quantity Threshold",
    UpperQuantityThresholdPlaceholder: "Input Upper Quantity Threshold",
    BatchLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(7) > nz-form-item > nz-switch > button",
    SelectAssetTypeLocator: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-transfer > nz-transfer-list:nth-child(1) > div.ant-transfer-list-header > label > span.ant-checkbox > input",
    SelectSingleAssetTypeLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-transfer > nz-transfer-list:nth-child(1) > div.ant-transfer-list-body.ant-transfer-list-body-with-search > ul > li:nth-child(1) > label > span.ant-checkbox > input",
    SelectSingleDeviceTypeLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-transfer > nz-transfer-list:nth-child(1) > div.ant-transfer-list-body.ant-transfer-list-body-with-search > ul > li:nth-child(1) > label > span.ant-checkbox > input",
    SelectAssetTypeNextLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-transfer > div > button:nth-child(2) > span > svg > path",
    EditAssetTypeNextLocator: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-transfer > div > button:nth-child(2) > span > svg",
    SelectDeviceTypeLocator: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-transfer > nz-transfer-list:nth-child(1) > div.ant-transfer-list-header > label > span.ant-checkbox > input",
    SelectDeviceTypeNextLocator: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-transfer > div > button:nth-child(2) > span > svg",
    EditDeviceTypeNextLocator: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-form-control > div > div > nz-transfer > div > button:nth-child(2) > span > svg",
    FormCancelSelector: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(5) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    UnitCancelSelector: "#screencontainer > div > app-part-type-create > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-invalid.ng-star-inserted.ng-touched.ng-dirty > div > div:nth-child(8) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    EditFormCancelSelector: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-star-inserted.ng-dirty.ng-invalid.ng-touched > div > div:nth-child(5) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    EditUnitCancelSelector: "#screencontainer > div > app-part-type-edit > div > div > nz-card > div.ant-card-body > div.ant-form.ant-form-vertical.ng-star-inserted.ng-dirty.ng-invalid.ng-touched > div > div:nth-child(8) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
    EditBatchLocator: 'nz-switch[formcontrolname="isbatch"] button.ant-switch-checked',
    CreateSuccess: "Part Type Created Successfully!!",
    UpdateSuccess: "Part Type Updated Successfully!!",
    Enter: "Enter",
    Select: "Control+A",
    Delete: "Backspace",
    NameAlert: "Please Input Part Type Name!",
    CodePrefixAlert: "Please Input Stock Code Prefix!",
    LowerThresholdAlert: "Invalid threshold!",
    UpperThresholdAlert: "Invalid threshold!",
    FormAlert: "Please Select Form!",
    UnitAlert: "Please Select Unit!",
    NameExistAlert: "parttype name - ",
    NameExistalert: " already exist",
    CodePrefixExistAlert: "stockcode prefix - ",
    CodePrefixExistalert: " already exist",
    DisableText: "Disable Part Type",
    DisableSuccess: "Part Type Disabled Successfully!",
    EnableText: "Enable Part Type",
    EnableSucess: "Part Type Enabled Successfully!",
    };

    export const storage_Location_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Cancel: "Cancel"
        },
        NamePlaceholder: "Input Storage location Name",
        StoreDropdownLocator: '.ant-select[formcontrolname="storeid"][nzplaceholder="Select Store"]',
        StoreCancelLocator: 'svg[data-icon="close-circle"]',
        CreateSuccess: "Storage Location Submitted Successfully!!",
        UpdateSuccess: "Storage Location Updated Successfully!!",
        Enter: "Enter",
        Select: "Control+A",
        Delete: "Backspace",
        StoreAlert: "Please Select a Store!",
        NameAlert: "Please Input Storage Location Name!",
        NameExistValidation: "Storage Location name already exist",
        DisableText: "Disable Storage Location",
        DisableSuccess: "Storage Location Disabled Successfully!",
        EnableText: "Enable Storage Location",
        EnableSucess: "Storage Location Enabled Successfully!",
    };
   
   
    



    export const inverter_dashboard = {
        DateSelector:"input[placeholder = 'Select date']",
        Enter:"Enter",
        InverterTodayText:"Today Energy",
        InverterMonthlyText:"Month Energy",
        InverterWeeklyText:"Weekly Energy",
        InverterTotalText:"Total Energy",
        InverterTodayLoactor:"app-today-energy",
        InverterWeeklyLocator:"app-week-energy",
        InverterMonthlyLocator:"app-month-energy",
        InverterTotalLocator:"app-total-energy",
        InverterPowerText:"Cumulative Inverter Power",
        InverterPowerMenuLocator:"app-cumulative-inverter app-menu",
        InverterExport:"Export csv",
        InverterPowerSuccessfull:"cumulative-inverter Downloaded Successfully",
        InverterPowerExpandLocator:"app-cumulative-inverter app-expand",
        InverterKpiText:"Inverter KPI\'s",
        InverterKpiExpandLocator:"app-inverter-kpi app-expand",
        InverterKpiMenuLocator:"app-inverter-kpi app-menu",
        InverterkpiPopMessage:"inverter-kpi Downloaded Successfully",
        LiveInverterText:"Inverter Performance Grid",
        LiveInverterDeviation:"app-info-button",
        LiveInverterMedian:"Median",
        LiveInverterMax:"Max",
        LiveInverterMenu:"app-live-inverter app-menu",
        LiveInverterExpand:"app-live-inverter app-expand",
        LiveInverterPr:"PR",
        LiveInverterYield:"Yield",
        LiveInverterAll:"All",
        LiveInverterModule:'Module',
        LiveInverter:'Inverter',
        LiveInverterTracker:"Tracker",
        LiveInverterNonTracker:"Non Tracker",
        LiveInverterMonitor:[
                'IS30 Inverter 1', 'IS30 Inverter 2', 'IS30 Inverter 3', 'IS30 Inverter 4', 'IS2 Inverter 1', 'IS2 Inverter 2', 'IS2 Inverter 3', 'IS2 Inverter 4', 'IS3 Inverter 1',
                'IS3 Inverter 2','IS3 Inverter 3','IS3 Inverter 4', 'IS4 Inverter 3','IS3 Inverter 4','IS4 Inverter 1','IS4 Inverter 2','IS4 Inverter 3','IS4 Inverter 4','IS5 Inverter 1',
                'IS5 Inverter 2','IS5 Inverter 3','IS5 Inverter 4','IS6 Inverter 1','IS6 Inverter 2','IS6 Inverter 3','IS6 Inverter 4','IS7 Inverter 1','IS7 Inverter 2','IS7 Inverter 3',
                'IS7 Inverter 4','IS8 Inverter 1','IS8 Inverter 2','IS8 Inverter 3','IS8 Inverter 4','IS9 Inverter 1','IS9 Inverter 2','IS9 Inverter 3','IS9 Inverter 4','IS10 Inverter 1',
                'IS10 Inverter 2','IS10 Inverter 3','IS10 Inverter 4','IS11 Inverter 1','IS11 Inverter 2','IS11 Inverter 3','IS11 Inverter 4','IS12 Inverter 1','IS12 Inverter 2','IS12 Inverter 3',
                'IS12 Inverter 4','IS13 Inverter 1','IS13 Inverter 2','IS13 Inverter 3','IS13 Inverter 4','IS14 Inverter 1','IS14 Inverter 2','IS14 Inverter 3',
              'IS14 Inverter 4','IS15 Inverter 1','IS15 Inverter 2','IS15 Inverter 3','IS15 Inverter 4','IS16 Inverter 1','IS16 Inverter 2','IS16 Inverter 3','IS16 Inverter 4'    
        ],
        InverterRankingText:"Inverter Ranking",
        InverterRankingLocator:"app-inverter-ranking",
        InverterRankingSort:"Inverter Name",
        InverterRankingSort01:"Inverter Availability(%)",
        InverterRankingSort02:"PR(%)",
        InverterRankingSort03:"Yield(MWh/MWp)",
        InverterRankingSort04:"Efficiency(%)",
        InverterRankingMenu:"app-inverter-ranking app-menu",
        InverterRankingExpand:"app-inverter-ranking app-expand",
        InverterHeatMapText:"Inverter Heatmap",
        HeatmapText:"Heatmap",
        InverterHeatmapPr:"PR",
        InverterHeatmapPrLoactor:"app-inverter-dashboard-heatmap-radio-group",
        InverterHeatmapYield:"Yield",
        InverterHeatmapEfficiency:"Efficiency",
        InverterHeatmapAvailability:"Inverter Availability(%)",
        InverterHeatmapExpand:"app-inverter-heatmap app-expand",
        InverterHeatmapMenu:"app-inverter-heatmap app-menu",
        InverterHeatmapMessage:"inverter-heatmap Downloaded Successfully",
       }
   
       export const Sacada_Heatmap_Production ={
        HeatmapProduction:"Heatmap / Production",
        ProductionPower:"Power",
        ProductionActivePower:"Active Power[MW]",
        ProductionDailyProduction:"Daily Production",
        ProductionPeakPower:"Peak Power",
        ProductionKPI:"KPI",
        ProductionPr:"PR",
        ProductionPa:"PA",
        ProductionCUFAC:"CUFAC",
        ProductionTotalGHI:"Total GHI",
        ProductionTotalPOA:"Total POA",
        ProductionHeatmapWMS:"WMS",
        ProductionModuleTemp:"Module Temp",
        ProductionAmbientTemp:"Ambient Temp",
        ForwardLocator:"i:nth-child(2) > svg",
        ProductionRelativeHumidity:"Relative Humidity",
        ProductionWindSpeed:"Wind Speed",
        BackwardLocator:"app-header > i > svg",
        ProductionHeaderText:"Production",
        SelectBlockLocator:"nz-select-top-control",
        SelectBlockPlaceHolder:"Select Block",
        ProductionBlockName:"IS30",
        ProductionBlockName01:"IS2",
        ProductionBlockName02:"IS6",
        ProductionBlockName03:"IS7",
        ProductionBlockName04:"IS5",
        ProductionBlockName05:"IS8",
        SelectBlock:['IS30', 'IS2', 'IS6', 'IS7'],
        ProductionExpand:"app-expand",
        HeatmapProductionPlant: [
            'ES Sun Power 20MW',
            'ES Energy Power 10MW',
            'ES Solar Power 10MW',
            'Dres Energy Pvt Ltd. 07MW',
            'Dres Energy Pvt Ltd. 08MW',
            'Prakreetee Solar Energy Godawari Private Limited',
          ],
          SelectBlockCloseLocator:"nz-select-clear svg",
    }
    
    export const Data_Availbality ={
        DataAvailbalityDashboard:"Dashboard",
        DataAvailbalityDatePicker:"nz-date-picker",
        DataAvailbalityBreadcrumb:"nz-breadcrumb button",
        DataAvailbalityClose:"nz-date-picker svg",
        TablePlantName:"Plant Name",
        TableAvailableData:"Available Data",
        TableNoData:"No Data",
        TableTool:"Tools",
        TableAvailable:"Available Data (%)",
        DataAvailbalityExport:"Export",
        DataAvailbalityBackButton:"Back",
        DeviceViewLocator:"#screencontainer > div > app-report-dashboard > div > div > nz-card > div.ant-card-body > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td.text-center.ant-table-cell > nz-space > div:nth-child(2) > button",
        DeviceViewClose:"nz-date-picker svg",
        DeviceNameSort:"Device Name",
        DeviceAvailableCount:"Available Count",
        DeviceAvailablePercentage:"Available Percentage",
        ViewOptionLocator:"#screencontainer > div > app-report-dashboard > div > div > nz-card > div.ant-card-body > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td.text-center.ant-table-cell > nz-space > div:nth-child(1) > button > span",
        ViewDeleteDate:"#screencontainer svg",
    }

    export const asset_Type_Variables = {
        operation: {
            create: "Add",
            save: "Save",
            Cancel: "Cancel"
        },
        NamePlaceholder: "Input Asset Type Name",
        CodePrefixPlaceholder: "Input Asset Type Code Prefix",
        FormDropdownLocator: '.ant-select[formcontrolname="formid"][nzplaceholder="Select Form"]',
        CreateSuccess: "Asset Type Created Successfully!!",
        UpdateSuccess: "Asset Type Updated Successfully!!",
        Enter: "Enter",
        Select: "Control+A",
        Delete: "Backspace",
        NameAlert: "Please Input Asset Type Name!",
        NameSizeAlert: "No of characters should be greater than 3!",
        CodePrefixSizeAlert: "Only Alphabets and numbers are allowed Enter a code of only 5 character",
        CodePrefixAlert: "Please Input Asset Type Code Prefix!",
        FormAlert: "Please Select Form!",
        FormCancelSelector: "#screencontainer > div > ng-component > div > div > nz-card > div.ant-card-body > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormEditCancelSelector: 'span[nztype="close-circle"]',
        NameExistAlert: "Asset Type Name ",
        NameExistalert: " already exist",
        CodePrefixExistAlert: "Asset Type Code prefix ",
        CodePrefixExistalert: " already exist",
        randomCodePrefix: generateRandomString(5),
    
    };

    export const Alert_Currentweek = {
        AlertDescription:"Description",
        AlertSearchDescription:"Search Description",
        AlertSearch:"Search",
        AlertDescriptionLocator:"nz-filter-trigger span",
        AlertPlant:"Plant Name",
        AlertPlantName:"CSBPL250MW",
        AlertPlantName01:"ESSP20MW",
        AlertPlantName02:"ESEP10MW",
        AlertPlantName03:"ESSP10MW",
        AlertPlantName04:"DRES7MW",
        AlertPlantName05:"DRES8MW",
        AlertPlantName06:"Panama10MW",
        AlertOK:"OK",
        AlertBlock:"Block Name",
        AlertBlockName:"DRES7MW_Block1",
        AlertBlockName01:"DRES8MW_Block1",
        AlertBlockName02:"Panama10MW_Block1",
        AlertBlockName03:"DRES7MW_Block2",
        AlertBlockName04:"DRES8MW_Block2",
        AlertBlockName05:"Panama10MW_Block2",
        AlertBlockName06:"ESEP10MW_Test B",
        AlertBlockName07:"DRES7MW_Block3",
        AlertDevice:"Device Name",
        AlertSearchDevice:"Search Device Display Name",
        AlertStatus:"Status",
        StatusLocator:"path",
        AlertLocator:'li',
        AlertStatusOn:"ALARM ON",
        AlertStatusOff:"ALARM OFF",
        AlertInactive:"Inactive At",
        Alertactive:"Active At",
        AlertDuration:"Duration(HH:mm)",  
        AlertSeverity:"Severity",
        AlertSeverityCheckBox:"CRITICAL",
        AlertSeverityCheckBox01:"HIGH",
        AlertSeverityCheckBox02:"MEDIUM",
        AlertSeverityCheckBox03:"LOW",
        AlertSeverityCheckBox04:"WARNING",
        AlertAcknowledge:"Acknowledged",
        AlertAcknowledge01:/^Acknowledged$/,
        AlertUnAcknowledged:"Un Acknowledged",
        AlertAcknowledgedAt:"Acknowledged At",
        AlertAcknowledgedAtLocator:"nz-filter-trigger span",
        AlertStartDate:"Start date",
        AlertEndDate:"End date",
        AlertAcknowledgedBy:"Acknowledged By",
        AlertAcknowledgedByLocator:"span",
        AlertAcknowledgedByCheckBox:"CMS (cms1@sgrids.io)",
        AlertTool:"Tools",
        AlertAdd:"Add",
        AlertAdd01:"Add Alert",
        AlertDropDownSelector:"nz-select-top-control",
        AlertAddPlantName:"Select a Plant Name",
        AlertAddPlantOption:"Clean Solar Power (Bhainsada) Private Limited 250MW",
        AlertAddBlockName:"Select a Block Name",
        AlertAddBlockOption:"CSBPL250MW IS30",
        AlertAddDeviceName:"Select a Device Name",
        AlertAddDeviceOption:"CSBPL250MW IS30 UPS",
        AlertAddParameterName:"Select a Parameter",
        AlertAddParameterOption:"testParam",
        AlertAddNotifictionName:"Select a Notification Name",
        AlertAddNotificationOption:"ISI",
        AlertSaveOption:"Save",
        AlertaddStartDate:"Start Date and Time",
        AlertStartDateLocator:"nz-form-item",
        AlertCalendarButton:"Now",
        AlertAddErrorMessage:"this alert is already exist",
        ALertAddSuccessfullMessage:"Data created sucessfully.!",
        AlertAddStatus:"Status",
        AlertAddStatusOn:"ON",
        AlertAddStatusOff:"OFF",
        AlertAddStatusDeleted:'Delete',
        AlertAddStatusEdit:'Edit',
        AlertDatePicker:'nz-date-picker',
        AlertAcknowledgedButton:"Acknowledge",
        AlertReload:"Reload",
        AlertExport:"Export",
        AlertReset:"Reset",
        AlertRemark:"Remark",
        AlertAcknowledgeRemark:"Acknowledge Remark",
        successfullMessage:'messages.acknowledgeSuccess',
        RemarkErrorMessage:'"remark" is not allowed to be empty',
    }

    export const Device = {
        DeviceParameterButton:'CSBPL250MW IS30 UPS UPS 192.168.29.172 Parameter Monitor',
        DeviceNotificationButton:"Notification",
        DeviceAddNotification:"Add Notification",
        DeviceDeleteButton:"ISI IS0 1 Edit Delete",
        DeviceOkButton:"OK",
        DeviceNoificationPlaceholder:"input notification name",
        NotificationTypeDropdown:"input notification type",
        NotificationLocator:'nz-select-top-control',
        NotificationLocator01:'textbox',
        NotificationComparison:"input notification comparison",
        NotificationSeverity:"select notification severity",
        DropdownOption:'ALERT',
        DropdownOption01:"EQUAL",
        DropdownOption02:"CRITICAL",
        NotificationDisplayPlaceholder:"input notification displayname",
        SaveOption:"Save",
        NotificationMessage:"Notification added successfully!!",
        ErrorMessage:'Notification IS0 already exist with the Parameter 65969397b328ca43ed228359',
        DeletedSuccessfully:"Device notification deleted successfully!!",
        NotificationDisplayName:"IS0",
        NotificationName:"ISI",
        RemarkText:"test",
    }

    export const approval_matrix_Variables = {
        operation: {
            create: "Add",
            save: "Save",
        },
        NamePlaceholder: "Input Approval Matrix Name",
        LabelPlaceholder: "Input Approval Label",
        NextButtonLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > ul > li.next > button > span:nth-child(1)",
        LabelOneLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(1) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormOneRequiredLocator: "nz-switch[formcontrolname='formrequired']",
        FormOneDropdownLocator: '#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(1) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input',
        PlusOneLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div > form > nz-card > div.ant-card-head.ng-star-inserted > div > div.ant-card-extra.ng-star-inserted > nz-space > div:nth-child(1) > span > button > span > svg",
        LabelTwoLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormTwoRequiredLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-switch > button",
        FormTwoDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        PlusTwoLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-head.ng-star-inserted > div > div.ant-card-extra.ng-star-inserted > nz-space > div:nth-child(1) > span > button > span > svg",
        LabelThreeLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormThreeRequiredLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-switch > button",
        FormThreeDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        PlusThreeLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-head.ng-star-inserted > div > div.ant-card-extra.ng-star-inserted > nz-space > div:nth-child(1) > span > button > span > svg",
        LabelFourLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormFourRequiredLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-switch > button",
        FormFourDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        PlusFourLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-head.ng-star-inserted > div > div.ant-card-extra.ng-star-inserted > nz-space > div:nth-child(1) > span > button > span > svg",
        LabelFiveLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > input",
        FormFiveRequiredLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div:nth-child(2) > nz-form-item > nz-switch > button",
        FormFiveDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        FormOneEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(1) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormTwoEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormThreeEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(3) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormFourEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(4) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        FormFiveEditDropdownLocator: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(5) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        CreateSuccess: "Approval Matrix Created Successfully!!",
        UpdateSuccess: "Approval Matrix Updated Successfully!!",
        Enter: "Enter",
        Select: "Control+A",
        Delete: "Backspace",
        Down: "ArrowDown",
        NameAlert: "Please Input Approval Matrix Name!",
        LabelOneAlert: "Please Input Approval Label!",
        FormAlert: "Please Select Form !",
        FormOneCancelSelector: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormTwoCancelSelector: "#screencontainer > div > app-approval-matrix-create-update > div > div > nz-card > div.ant-card-body > div > div:nth-child(2) > div:nth-child(2) > form > nz-card > div.ant-card-body > div > div.ant-col.ant-col-24 > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span > svg",
        FormEditCancelSelector: 'span[nztype="close-circle"]',
        PaginationLocator: "#screencontainer > div > app-approval-matrix-dashboard > div > div > nz-card > div.ant-card-body > nz-table > nz-spin > div > nz-pagination > ul > li.ant-pagination-options.ng-star-inserted > nz-select > nz-select-top-control > nz-select-item",
        MatrixNameExistAlert: "Approval matrix name ",
        MatrixNameExistalert: " exist",
        DuplicateApprovalLabelAlert: "Duplicate approval approvallabel added",
    
    };

    export const approval_matrix_map_Variables = {
        operation: {
            create: "Add",
            save: "Save",
        },
        ApprovalMatrixLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        PlantLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-search > input",
        ApproverOneLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverTwoLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverThreeLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverFourLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverFiveLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        Enter: "Enter",
        Down: "ArrowDown",
        EditText: "Edit Matrix Map",
        CreateSuccess: "Approval Matrix Map Created Successfully!!",
        ApprovalMatrixCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        PlantCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApprovalMatrixAlert: "Please Select Approval Matrix!",
        PlantAlert: "Please Select Plant!",
        ApproverOneCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverTwoCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverThreeCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverFourCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverFiveCancelLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-clear > span",
        ApproverOneAlertLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control",
        ApproverTwoAlertLocator: '#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control',
        ApproverThreeAlertLocator: '#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control',
        ApproverFourAlertLocator: '#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control',
        ApproverFiveAlertLocator: '#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control',
        PaginationLocator: "#screencontainer > div > app-approval-matrix-map-dashboard > div > div > nz-card > div.ant-card-body > nz-table > nz-spin > div > nz-pagination > ul > li.ant-pagination-options.ng-star-inserted > nz-select > nz-select-top-control",
        ApprovalMatrixEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        PlantEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div.ant-form.ant-form-vertical.ng-star-inserted > nz-card > div > div > div > div:nth-child(1) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control > nz-select-item",
        ApproverOneEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(1) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverTwoEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(2) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverThreeEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(3) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverFourEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(4) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        ApproverFiveEditLocator: "#screencontainer > div > app-approval-matrix-map-createmanage > div > div > nz-card > div.ant-card-body > div > div > div:nth-child(2) > nz-table > nz-spin > div > div > nz-table-inner-default > div > table > tbody > tr:nth-child(5) > td:nth-child(3) > nz-form-item > nz-form-control > div > div > nz-select > nz-select-top-control",
        UpdateSuccess: "Approval Matrix Map Updated Successfully!!",
    };


